export const PRODUCTS = [
  {
    id: "1",
    name: "Classic Crunchy",
    description: "The original taste that started it all. Perfectly golden and crunchy.",
    price: 1500,
    image: "/images/classic-crunchy.jpg", // Placeholder - in real app would be real URL
    category: "Classic",
  },
  {
    id: "2",
    name: "Spicy Fiesta",
    description: "A kick of heat with every bite. For those who love a little spice.",
    price: 1600,
    image: "/images/spicy-fiesta.jpg",
    category: "Special",
  },
  {
    id: "3",
    name: "Vanilla Dream",
    description: "Sweet and aromatic vanilla flavor. A perfect dessert snack.",
    price: 1600,
    image: "/images/vanilla-dream.jpg",
    category: "Sweet",
  },
  {
    id: "4",
    name: "Coconut Bliss",
    description: "Infused with real coconut shavings for a tropical twist.",
    price: 1700,
    image: "/images/coconut-bliss.jpg",
    category: "Sweet",
  },
  {
    id: "5",
    name: "Cinnamon Swirl",
    description: "Dusting of cinnamon sugar for a warm, comforting taste.",
    price: 1600,
    image: "/images/cinnamon.jpg",
    category: "Sweet",
  },
  {
    id: "6",
    name: "Nutmeg Delight",
    description: "Enhanced with rich nutmeg flavor. A holiday favorite.",
    price: 1600,
    image: "/images/nutmeg.jpg",
    category: "Classic",
  },
  {
    id: "7",
    name: "Chocolate Chip",
    description: "Mini chocolate chips embedded in every piece.",
    price: 1800,
    image: "/images/chocolate.jpg",
    category: "Sweet",
  },
  {
    id: "8",
    name: "Ginger Snap",
    description: "Zesty ginger flavor that wakes up your taste buds.",
    price: 1600,
    image: "/images/ginger.jpg",
    category: "Special",
  },
  {
    id: "9",
    name: "Onion & Garlic",
    description: "Savory blend of onion and garlic. Ideally paired with dips.",
    price: 1600,
    image: "/images/onion-garlic.jpg",
    category: "Savory",
  },
  {
    id: "10",
    name: "Honey Glazed",
    description: "Sweet honey coating for a sticky, delicious treat.",
    price: 1700,
    image: "/images/honey.jpg",
    category: "Sweet",
  },
  {
    id: "11",
    name: "Salted Caramel",
    description: "Rich caramel flavor with a hint of sea salt.",
    price: 1800,
    image: "/images/salted-caramel.jpg",
    category: "Sweet",
  },
  {
    id: "12",
    name: "Cheese Explosion",
    description: "Savory cheese flavor that melts in your mouth.",
    price: 1700,
    image: "/images/cheese.jpg",
    category: "Savory",
  },
];

export const ORDERS = [
  {
    id: "ORD-1234",
    date: "2024-02-15T10:30:00Z",
    status: "Pending" as const,
    total: 3200,
    items: [
      { name: "Classic Crunchy", quantity: 2 },
    ],
    address: "123 Main St, Lagos",
  },
  {
    id: "ORD-5678",
    date: "2024-02-10T14:15:00Z",
    status: "Delivered" as const,
    total: 4800,
    items: [
      { name: "Spicy Fiesta", quantity: 1 },
      { name: "Vanilla Dream", quantity: 2 },
    ],
    address: "456 Park Ave, Abuja",
  },
  {
    id: "ORD-9012",
    date: "2024-02-14T09:00:00Z",
    status: "Out for Delivery" as const,
    total: 1600,
    items: [
      { name: "Coconut Bliss", quantity: 1 },
    ],
    address: "789 Beach Rd, Port Harcourt",
  },
];
